### ISSUE TITLE
Request: Create a new release

### ISSUE THREAD

**Issue by Namnodorel** [JLouis-B/RedTools#2]
There have been a lot of changes and relevant bug fixes since 2.10 - but they are currently only usable for people who have the ability to build the project themselves.
Why not create a new release to share the improvements with the public? :D

**Comment by JLouis-B** [comment]
Hi,
Yes, it's planned !
I'm just testing and finalizing a new build and I was thinking of publishing a new version in the next few days :)

**Comment by Namnodorel** [comment]
Ah, that's great ^^ Looking forward to it :)
