### ISSUE TITLE
Building RedTools

### ISSUE THREAD

**Issue by dennisgranasen** [JLouis-B/RedTools#3]
I'm trying to build against the current version of irrlicht (1.8.4), but it fails due to a few missing methods. Have there been breaking changes in irrlicht API perhaps?

Example below:
```
D:\dev\RedTools\W2ENT_QT\MeshCombiner.cpp:104: error: 'class irr::scene::IMesh' has no member named 'getMeshType'; did you mean 'getMeshBuffer'?
     if (addition->getMeshType() != scene::EAMT_SKINNED || !preserveBones)
                   ^~~~~~~~~~~
                   getMeshBuffer
```

**Comment by JLouis-B** [comment]
Hi,
Yes, Irrlicht 1.8.4 will not work, I use some changes of the current dev version.
I've added some info for the compilation [here](https://github.com/JLouis-B/RedTools/wiki/Compilation).

**Comment by strazto** [comment]
@JLouis-B , would you mind forking Irrlicht with your specific patches applied & hosting that fork so it's straightforward to replicate your build env?

**Comment by JLouis-B** [comment]
Hi,
Thank you for the suggestion.
However I prefer not to create my own Irrlicht repo, simply to be able to benefit from engine changes without having to manage a fork and update it regularly.
For the moment the only part to patch is the loading of the DDS files, which doesn't seem excessive (and I would like this fix to be integrated into the engine, I'll have to check it with the irrlicht maintainer).
If at some point I had to make a lot more modifications on the engine it would be possible not now.

If you have difficulties to integrate these modifications please ask :)
