### ISSUE TITLE
faulty fbx export

### ISSUE THREAD

**Issue by SaintBahamut** [JLouis-B/RedTools#4]
hello

tried to export some armor meshes as fbx, program produced empty (p byte) file

**Comment by JLouis-B** [comment]
Hi,
Thank you for the report.
This bug has already been reported to me and it is corrected in the current code.
The correction will be available in the next version (no date for that but probably before the end of the year, a few things to finish before that).
In the meantime you can use all exporters not using Assimp library.

**Comment by JLouis-B** [comment]
Fixed in the 2.13 release
